volumes:
  dynamodb:

services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "127.0.0.1:18000:8000"
    volumes:
      - type: volume
        source: dynamodb
        target: /home/dynamodblocal/data
    working_dir: /home/dynamodblocal
